[workspace]
members = [
    "wavesyncdb", 
    "wavesyncdb-derive"
    # "examples/*"
]
# exclude = ["examples"]
resolver = "3"

[workspace.dependencies]
wavesyncdb = { path = "wavesyncdb", version = "0.2.0"}