[package]
name = "example-p2p"
version = "0.2.0"
edition = "2024"

[dependencies]
log = { workspace = true }
env_logger = "0.10.0"
wavesyncdb = { workspace = true }
wavesyncdb_derive = { workspace = true }
sea-orm = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
