[package]
name = "wavesyncdb"
version = "0.3.0"
edition = "2024"
license = "GPL-3.0-or-later"
description = "WaveSyncDB is a lightweight, distributed database synchronization engine designed to bridge the gap between real-time data streaming and relational storage. It ensures high-consistency data replication across decentralized nodes with a focus on low-latency updates."
repository = "https://github.com/pvg13/WaveSyncDB"
readme = "README.md"

[dependencies]
sea-orm = { workspace = true }
uhlc = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
libp2p = { workspace = true }
libp2p-swarm-derive = "0.35.1"
log = { workspace = true }
thiserror = { workspace = true }
serde_json = "1.0"
uuid = { workspace = true }
inventory = { workspace = true }
