[package]
name = "wavesyncdb"
version = "0.2.0"
edition = "2024"
license = "GPL-3.0-or-later"
description = "WaveSyncDB is a lightweight, distributed database synchronization engine designed to bridge the gap between real-time data streaming and relational storage. It ensures high-consistency data replication across decentralized nodes with a focus on low-latency updates."
repository = "https://github.com/pvg13/WaveSyncDB"
readme = "README.md"

[dependencies]
chrono = "0.4.42"
diesel = { version = "2.3.2", features = ["chrono", "i-implement-a-third-party-backend-and-opt-into-breaking-changes", "uuid"]}
libp2p = { version = "0.56.0", features = ["gossipsub", "identify", "mdns", "ping", "quic", "request-response", "serde", "tokio", "noise", "yamux", "tcp"] }
libp2p-swarm-derive = "0.35.1"
log = "0.4.28"
sqlparser = "0.58.0"
tokio = { version = "1.47.1", features = ["full"] }


[features]
default = ["sqlite"]
sqlite = ["diesel/sqlite", "diesel/returning_clauses_for_sqlite_3_35"]
postgres = ["diesel/postgres"]
mysql = ["diesel/mysql"]


[dev-dependencies]
tokio = { version = "1.47.1", features = ["full"] }
diesel ={ version = "2.3.2", features = ["sqlite", "r2d2"]}
