[package]
name = "wavesyncdb"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
diesel = { version = "2.3.2", features = ["chrono", "i-implement-a-third-party-backend-and-opt-into-breaking-changes", "returning_clauses_for_sqlite_3_35", "sqlite", "uuid"]}
diesel-async = { version = "0.7.4", features = ["sqlite", "migrations", "pool", "deadpool"] }
libp2p = { version = "0.56.0", features = ["gossipsub", "identify", "mdns", "ping", "quic", "request-response", "serde"] }
libp2p-swarm-derive = "0.35.1"
log = "0.4.28"
sqlparser = "0.58.0"
tokio = { version = "1.47.1", features = ["full"] }

